name: dedalus3
channels:
  - conda-forge
dependencies:
  - cartopy==0.24.0
  - dask==2025.2.0
  - dedalus==3.0.3
  - ipykernel==6.29.5
  - jupyter==1.1.1
  - matplotlib==3.10.0
  - netcdf4==1.7.2
  - numpy==2.2.3
  - pandas==2.2.3
  - python=3.12.9
  - scikit-learn==1.6.1
  - scipy==1.15.1
  - xarray==2025.1.2
  - zarr==3.0.2
  - ca-certificates==2025.4.26
  - certifi==2025.4.26
  - openssl==3.5.0
  - xesmf==0.9.2
  - mpi=1.0
  - mpi4py=4.0.3
  - openmpi=5.0.6
  - pip:
      - pycwt==0.5.0b0
variables:
  NUMEXPR_MAX_THREADS: '1'
  OMP_NUM_THREADS: '1'
